import { LitElement,css,html,nothing } from "lit";
import type { HomeAssistant } from "custom-card-helpers";
import type { AutomationScenarioConfig,LinkedAutomationConfig } from "../../automation/automation-scenario.types.ts";
import type { EntitySelectedDetail } from "../../components/entity-selector.ts";
import { createLinkedAutomation,createScenarioFromPreset,scenarioBlueprintRecommendations,validateScenarioDraftForEditor,type AutomationScenarioPreset } from "./automation-editor-helpers.ts";
import "../../components/common/app-dialog.ts";
import "../../components/common/button.ts";
import "../../components/common/field.ts";
import "../../components/common/select-item.ts";
import "../../components/entity-selector.ts";

export interface ScenarioCreatedDetail { scenario:AutomationScenarioConfig; }
type Step="choose"|"create"|"blueprint"|"picker"|"duplicate";
type PickerTarget={kind:"status"}|{kind:"automation";groupId:string};

export class AutomationScenarioCreationFlow extends LitElement {
  static properties={open:{type:Boolean,reflect:true},hass:{attribute:false},existingIds:{attribute:false},step:{state:true},preset:{state:true},draft:{state:true},pickerTarget:{state:true},errors:{state:true},pickerError:{state:true},duplicateEntity:{state:true},duplicateGroupId:{state:true}};
  open=false; hass?:HomeAssistant; existingIds:string[]=[];
  private step:Step="choose"; private preset:AutomationScenarioPreset="blank"; private draft?:AutomationScenarioConfig;
  private pickerTarget?:PickerTarget; private errors:string[]=[]; private pickerError="";
  private duplicateEntity=""; private duplicateGroupId="";

  static styles=css`
    :host{display:contents} ic-app-dialog{--dialog-width:min(760px,calc(100vw - 32px))}
    .flow{display:grid;min-width:0;gap:18px;box-sizing:border-box;padding:12px 16px 16px;container-type:inline-size}
    .templates,.groups{display:grid;gap:8px}.copy{margin:0;color:var(--secondary-text-color);font-size:13px;line-height:1.5}
    .section-heading{display:flex;align-items:center;justify-content:space-between;gap:12px}.section-heading h4{margin:0;font-size:13px}.optional{color:var(--secondary-text-color);font-size:12px}
    .fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px 16px}.binding{display:grid;gap:6px}.label{font-size:13px;font-weight:600}
    .binding button{width:100%;min-width:0;overflow:hidden;padding:12px 14px;border:var(--ic-border-control,var(--en-border));border-radius:var(--en-control-radius,12px);background:var(--ic-control-background,var(--en-surface-control));color:var(--secondary-text-color);font:inherit;text-align:left;text-overflow:ellipsis;white-space:nowrap;cursor:pointer}
    .group{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:12px;padding:11px 13px;border:var(--ic-border-control,var(--en-border));border-radius:var(--en-panel-radius,14px);background:var(--ic-control-background,var(--en-surface-control))}.group-copy{display:grid;min-width:0;gap:3px}.group-copy span{color:var(--secondary-text-color);font-size:12px}.linked{margin:4px 0 0;padding-left:16px;color:var(--secondary-text-color);font-size:12px}
    .footer{display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:10px}.footer-right{display:flex;gap:8px}.errors{display:grid;gap:4px;color:var(--error-color);font-size:12px}
    .recommendations{display:flex;flex-wrap:wrap;gap:7px}.recommendation{padding:6px 10px;border-radius:999px;background:var(--ic-control-background,var(--en-surface-control));color:var(--secondary-text-color);font-size:12px}
    .empty-automations{display:grid;gap:8px;padding:8px 0}.empty-automations strong{font-size:13px}.empty-automations span{color:var(--secondary-text-color);font-size:12px}.empty-automations ic-button{justify-self:start}
    @container(max-width:540px){.flow{padding:8px 10px 12px}.fields{grid-template-columns:1fr}.group{grid-template-columns:1fr}.group ic-button{justify-self:start}}
  `;

  protected updated(changed:Map<PropertyKey,unknown>){if(changed.has("open")&&this.open&&!changed.get("open"))this.reset();}
  private reset(){this.step="choose";this.draft=undefined;this.errors=[];this.pickerError="";this.pickerTarget=undefined;this.duplicateEntity="";}
  private close(){this.dispatchEvent(new CustomEvent("scenario-creation-close",{bubbles:true,composed:true}));}
  private choose(preset:AutomationScenarioPreset){this.preset=preset;this.draft=createScenarioFromPreset(preset,"",this.existingIds);this.step="create";}
  private friendly(entity:string){return String(this.hass?.states[entity]?.attributes.friendly_name??entity);}
  private openPicker(target:PickerTarget){this.pickerTarget=target;this.pickerError="";this.step="picker";}
  private selected(entityId:string){if(!this.draft||!this.pickerTarget)return;if(this.pickerTarget.kind==="status"){this.draft={...this.draft,status_entity:entityId};this.step="create";this.pickerTarget=undefined;return;}if(!entityId.startsWith("automation.")){this.pickerError="Select an automation entity.";return;}this.linkAutomation(this.pickerTarget.groupId,entityId);}
  private findLinked(entity:string){for(const group of this.draft?.automation_groups??[]){const automation=group.automations.find(item=>item.entity===entity);if(automation)return{group,automation};}return undefined;}
  private linkAutomation(groupId:string,entity:string){if(!entity.startsWith("automation.")){this.pickerError="Select an automation entity.";return;}const duplicate=this.findLinked(entity);if(duplicate){this.duplicateEntity=entity;this.duplicateGroupId=groupId;this.step="duplicate";return;}this.addLinked(groupId,createLinkedAutomation(entity,this.friendly(entity),(this.draft?.automation_groups??[]).flatMap(group=>group.automations.map(item=>item.id))));this.step="create";this.pickerTarget=undefined;}
  private addLinked(groupId:string,automation:LinkedAutomationConfig){if(!this.draft)return;this.draft={...this.draft,automation_groups:(this.draft.automation_groups??[]).map(group=>group.id===groupId?{...group,automations:[...group.automations,automation]}:group)};}
  private moveDuplicate(){const found=this.findLinked(this.duplicateEntity);if(!found||!this.draft)return;this.draft={...this.draft,automation_groups:(this.draft.automation_groups??[]).map(group=>({...group,automations:group.id===found.group.id?group.automations.filter(item=>item!==found.automation):group.id===this.duplicateGroupId?[...group.automations,found.automation]:group.automations}))};this.step="create";this.pickerTarget=undefined;}
  private linkDefaultGroup(){if(!this.draft)return;const existing=this.draft.automation_groups??[];if(existing.length){this.openPicker({kind:"automation",groupId:existing[0]!.id});return;}const group={id:"automations",label:"Automations",automations:[]};this.draft={...this.draft,automation_groups:[group]};this.openPicker({kind:"automation",groupId:group.id});}
  private automationErrors(){return (this.draft?.automation_groups??[]).flatMap(group=>group.automations.filter(item=>!item.entity.startsWith("automation.")).map(()=>"Select an automation entity."));}
  private save(){if(!this.draft)return;this.errors=[...validateScenarioDraftForEditor(this.draft),...this.automationErrors()];if(this.errors.length){this.step="create";return;}this.dispatchEvent(new CustomEvent<ScenarioCreatedDetail>("scenario-created",{detail:{scenario:this.draft},bubbles:true,composed:true}));}

  render(){return html`<ic-app-dialog .open=${this.open} title="Add Scenario" @dialog-close=${this.close}><div class="flow">${this.renderStep()}</div></ic-app-dialog>`;}
  private renderStep(){if(this.step==="choose")return this.renderChoose();if(this.step==="picker")return this.renderPicker();if(this.step==="duplicate")return this.renderDuplicate();if(this.step==="blueprint")return this.renderBlueprint();if(!this.draft)return nothing;return this.renderCreate();}
  private renderChoose(){const choices:[AutomationScenarioPreset,string,string,string][]=[["pet_care","Pet Care","Feeding, environment and monitoring","mdi:paw"],["solar_water_heating","Solar Water Heating","Solar-priority hot water control","mdi:water-boiler"],["ev_smart_charging","EV Charging","Smart charging and departure targets","mdi:ev-station"],["blank","Blank Scenario","Build your own","mdi:plus"]];return html`<div><h3>Choose Starting Point</h3><div class="templates">${choices.map(([preset,label,description,icon])=>html`<ic-select-item .displayLabel=${label} .secondaryLabel=${description} @click=${()=>this.choose(preset)}><ha-icon .icon=${icon}></ha-icon> ${label}<span slot="secondary">${description}</span><ha-icon slot="trailing" icon="mdi:chevron-right"></ha-icon></ic-select-item>`)}</div></div>`;}
  private renderCreate(){const draft=this.draft!,groups=draft.automation_groups??[],automationErrors=this.automationErrors(),valid=validateScenarioDraftForEditor(draft).filter(error=>error.includes("Scenario Name")||error.includes("Status Entity")).length===0&&!automationErrors.length,displayErrors=[...this.errors,...automationErrors];return html`<div><h3>${draft.identity?.title}</h3></div><div class="section-heading"><h4>Scenario</h4></div><div class="fields"><ic-field label="Scenario Name *" .value=${draft.identity?.title??""} @field-change=${(e:CustomEvent<{value:string}>)=>{this.draft={...draft,identity:{...(draft.identity??{}),title:e.detail.value}};}}></ic-field><div class="binding"><span class="label">Status Entity *</span><button @click=${()=>this.openPicker({kind:"status"})}>${draft.status_entity?this.friendly(draft.status_entity):"Select entity"}</button></div></div><div class="section-heading"><h4>Automations</h4><span class="optional">Optional</span></div><div class="groups">${groups.length?groups.map(group=>html`<div class="group"><div class="group-copy"><strong>${group.label}</strong><span>${group.automations.length?`${group.automations.length} linked automation${group.automations.length===1?"":"s"}`:"No automations linked"}</span>${group.automations.map(item=>html`<div class="linked">${item.name??item.entity}</div>`)}</div><ic-button variant="secondary" @click=${()=>this.openPicker({kind:"automation",groupId:group.id})}>+ Link Automation</ic-button></div>`):html`<div class="empty-automations"><strong>No automations linked yet.</strong><span>You can add them now or later.</span><ic-button variant="secondary" @click=${this.linkDefaultGroup}>+ Link Automation</ic-button></div>`}</div>${scenarioBlueprintRecommendations[this.preset].length?html`<div class="recommendations">${scenarioBlueprintRecommendations[this.preset].map(item=>html`<span class="recommendation">${item}</span>`)}</div>`:nothing}${displayErrors.length?html`<div class="errors">${displayErrors.map(error=>html`<span>${error}</span>`)}</div>`:nothing}<div class="footer"><ic-button @click=${()=>{this.step="choose";}}>Back</ic-button><div class="footer-right"><ic-button variant="secondary" @click=${()=>{this.step="blueprint";}}>Use Blueprint</ic-button><ic-button variant="primary" .disabled=${!valid} @click=${this.save}>Create Scenario</ic-button></div></div>`;}
  private renderPicker(){const automation=this.pickerTarget?.kind==="automation";return html`<div><h3>${automation?"Select Automation":"Select Status Entity"}</h3><p class="copy">${automation?"Choose an existing Home Assistant automation.":"Choose the entity that represents this Scenario's current status."}</p></div><ic-entity-selector variant="inline" .hass=${this.hass} .filter=${automation?{domains:["automation"]}:{}} .placeholder=${automation?"Search automations":"Search entities"} @entity-selected=${(e:CustomEvent<EntitySelectedDetail>)=>this.selected(e.detail.entityId)}></ic-entity-selector>${this.pickerError?html`<div class="errors"><span>${this.pickerError}</span></div>`:nothing}<div class="footer"><ic-button @click=${()=>{this.step="create";this.pickerTarget=undefined;this.pickerError="";}}>Back</ic-button></div>`;}
  private renderDuplicate(){const found=this.findLinked(this.duplicateEntity);return html`<div><h3>Automation already linked</h3><p class="copy"><strong>${this.friendly(this.duplicateEntity)}</strong> is already linked to <strong>${found?.group.label}</strong>.</p></div><div class="footer"><ic-button @click=${()=>{this.step="picker";}}>Cancel</ic-button><ic-button variant="primary" @click=${this.moveDuplicate}>Move here</ic-button></div>`;}
  private renderBlueprint(){return html`<div><h3>Create from Blueprint</h3><p class="copy">Blueprint automations are created by Home Assistant.</p><ol class="copy"><li>Open Home Assistant Blueprints.</li><li>Create an automation from a Blueprint.</li><li>Return here.</li><li>Link the created Automation.</li></ol><div class="recommendations">${scenarioBlueprintRecommendations[this.preset].map(item=>html`<span class="recommendation">${item}</span>`)}</div><p class="copy">A stable public Blueprint navigation target is not available to this custom card, so no unverified URL is opened.</p></div><div class="footer"><ic-button @click=${()=>{this.step="create";}}>Back</ic-button><div class="footer-right"><ic-button .disabled=${true}>Open Home Assistant</ic-button><ic-button variant="primary" @click=${()=>{const first=this.draft?.automation_groups?.[0];if(first)this.openPicker({kind:"automation",groupId:first.id});else this.linkDefaultGroup();}}>I've Created It</ic-button></div></div>`;}
}
if(!customElements.get("automation-scenario-creation-flow"))customElements.define("automation-scenario-creation-flow",AutomationScenarioCreationFlow);
